'use server';
/**
 * @fileOverview This file defines a Genkit flow for answering voice queries from farmers, integrating relevant information
 * such as local schemes, weather, and market prices.
 *
 * - answerVoiceQueryWithIntegratedInfo - A function that takes a voice query and returns an advice.
 * - AnswerVoiceQueryWithIntegratedInfoInput - The input type for the answerVoiceQueryWithIntegratedInfo function.
 * - AnswerVoiceQueryWithIntegratedInfoOutput - The return type for the answerVoiceQueryWithIntegratedInfo function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnswerVoiceQueryWithIntegratedInfoInputSchema = z.object({
  query: z.string().describe('The voice query from the farmer.'),
  location: z.string().optional().describe('The location of the farmer, if available.'),
  chatHistory: z.array(z.object({speaker: z.enum(['USER', 'AI']), text: z.string()})).optional().describe('The history of the conversation with the user.'),
});
export type AnswerVoiceQueryWithIntegratedInfoInput = z.infer<typeof AnswerVoiceQueryWithIntegratedInfoInputSchema>;

const AnswerVoiceQueryWithIntegratedInfoOutputSchema = z.object({
  advice: z.string().describe('The advice generated by the AI assistant.'),
});
export type AnswerVoiceQueryWithIntegratedInfoOutput = z.infer<typeof AnswerVoiceQueryWithIntegratedInfoOutputSchema>;

export async function answerVoiceQueryWithIntegratedInfo(input: AnswerVoiceQueryWithIntegratedInfoInput): Promise<AnswerVoiceQueryWithIntegratedInfoOutput> {
  return answerVoiceQueryWithIntegratedInfoFlow(input);
}

const answerVoiceQueryWithIntegratedInfoPrompt = ai.definePrompt({
  name: 'answerVoiceQueryWithIntegratedInfoPrompt',
  input: {schema: AnswerVoiceQueryWithIntegratedInfoInputSchema},
  output: {schema: AnswerVoiceQueryWithIntegratedInfoOutputSchema},
  prompt: `You are an AI assistant for farmers. You answer questions based on the user query, their location, and the chat history.

      User Query: {{{query}}}
      Location: {{{location}}}
      Chat History: {{#each chatHistory}}{{{speaker}}}: {{{text}}}\n{{/each}}

      Please provide clear and helpful advice to the farmer.
      Integrate relevant information about local schemes, weather, and market prices into the response if available and applicable.
`,
});

const answerVoiceQueryWithIntegratedInfoFlow = ai.defineFlow(
  {
    name: 'answerVoiceQueryWithIntegratedInfoFlow',
    inputSchema: AnswerVoiceQueryWithIntegratedInfoInputSchema,
    outputSchema: AnswerVoiceQueryWithIntegratedInfoOutputSchema,
  },
  async input => {
    const {output} = await answerVoiceQueryWithIntegratedInfoPrompt(input);
    return output!;
  }
);

