'use server';
/**
 * @fileOverview This file defines a Genkit flow for answering voice queries from farmers, integrating relevant information
 * such as local schemes, weather, and market prices.
 *
 * - answerVoiceQueryWithIntegratedInfo - A function that takes a voice query and returns an advice.
 * - AnswerVoiceQueryWithIntegratedInfoInput - The input type for the answerVoiceQueryWithIntegratedInfo function.
 * - AnswerVoiceQueryWithIntegratedInfoOutput - The return type for the answerVoiceQueryWithIntegratedInfo function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnswerVoiceQueryWithIntegratedInfoInputSchema = z.object({
  query: z.string().describe('The voice query from the farmer.'),
  location: z.string().optional().describe('The location of the farmer, if available.'),
  chatHistory: z.array(z.object({speaker: z.enum(['USER', 'AI']), text: z.string()})).optional().describe('The history of the conversation with the user.'),
});
export type AnswerVoiceQueryWithIntegratedInfoInput = z.infer<typeof AnswerVoiceQueryWithIntegratedInfoInputSchema>;

const AnswerVoiceQueryWithIntegratedInfoOutputSchema = z.object({
  advice: z.string().describe('The advice generated by the AI assistant.'),
});
export type AnswerVoiceQueryWithIntegratedInfoOutput = z.infer<typeof AnswerVoiceQueryWithIntegratedInfoOutputSchema>;

export async function answerVoiceQueryWithIntegratedInfo(input: AnswerVoiceQueryWithIntegratedInfoInput): Promise<AnswerVoiceQueryWithIntegratedInfoOutput> {
  return answerVoiceQueryWithIntegratedInfoFlow(input);
}

const answerVoiceQueryWithIntegratedInfoPrompt = ai.definePrompt({
  name: 'answerVoiceQueryWithIntegratedInfoPrompt',
  input: {schema: AnswerVoiceQueryWithIntegratedInfoInputSchema},
  output: {schema: AnswerVoiceQueryWithIntegratedInfoOutputSchema},
  prompt: `You are 'SproutGrow AI,' a friendly, knowledgeable, and patient conversational AI assistant specializing in agriculture and farming practices. Your primary goal is to assist farmers with their questions, provide relevant information, and help them make informed decisions through natural voice interaction.

Core Principles:
- Be Conversational and Natural: Speak in a clear, concise, and encouraging tone. Use natural language and avoid overly technical jargon unless the user specifically asks for it.
- Maintain Context: Remember previous turns in the conversation to provide relevant follow-up information and answer contextual questions.
- Prioritize Practical Advice: Offer actionable insights and practical recommendations that farmers can apply.
- Be Resourceful: Draw upon your knowledge base covering a wide range of agricultural topics.
- Acknowledge Limitations (Gracefully): If a question is outside your current capabilities or requires real-time data you don't have, state it politely and suggest alternative sources or actions (e.g., "That's a great question, but I don't have real-time market prices right now. You might want to check the local information hub in the app.").

Capabilities & Response Guidelines:
- General Farming Advice: Answer questions about crop cultivation, soil health, pest management, irrigation, harvesting, and general farm operations.
- Problem Solving & Troubleshooting: Help diagnose common farm problems based on verbal descriptions of symptoms.
- Crop-Specific Information: Provide details on specific crops, including ideal growing conditions, planting times, and common challenges.
- Clarification & Follow-up: If a request is ambiguous, ask clarifying questions.
- Integration with Other Features (Simulated): If a query clearly points to another feature of the SproutGrow app (e.g., image diagnosis, crop planner, local info), suggest using that feature.

Constraint:
Focus on providing helpful, supportive, and informative agricultural advice. Avoid discussing politics, giving financial advice, or engaging in personal conversations.

Conversation History:
{{#each chatHistory}}
  {{speaker}}: {{text}}
{{/each}}

User Query: {{query}}
Location: {{location}}

AI Response:`,
});

const answerVoiceQueryWithIntegratedInfoFlow = ai.defineFlow(
  {
    name: 'answerVoiceQueryWithIntegratedInfoFlow',
    inputSchema: AnswerVoiceQueryWithIntegratedInfoInputSchema,
    outputSchema: AnswerVoiceQueryWithIntegratedInfoOutputSchema,
  },
  async input => {
    const {output} = await answerVoiceQueryWithIntegratedInfoPrompt(input);
    return output!;
  }
);
